print("Sergio Ibañez Montiel")
print(" Fortalezas: ")
print("1.-Soy responsable")
print("2.-Soy puntual")
print("3.-Soy empatico")
print(" Debilidades: ")
print("1.-A veces soy muy distraido")
print("2.-No me gusta la lectura")
print("3.-Soy un poco impaciente")
print(" Logros: ")
print("1.-Ser Ingeniero en Sistemas Computacionales y maestro en Tecnologias de la Informacion")
print("2.-Aprender a tocar la bateria acustica")
print("3.-Aprender a programar")
print(" Musica y Artistas favoritos: ")
print("Artistas:")
print("1.-Balck eyes Peas")
print("2.-Eminem")
print("3.-Green Day")
print("Musica: ")
print("1.-Hip Hop")
print("2.-Pop")
print("3.-Rock")    
print(" Vacaciones: ")
print("En mis vacaciones hice un salto desde una avioneta a mas de 17 mil pies de altura, " \
"fuí a Val-Quirico, Cholula Puebla y practicar trail running.")